version: "3.8"
services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: ekyc_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password1
      MYSQL_DATABASE: ekyc
    volumes:
      - ./config/mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=caching_sha2_password

  mysqladmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysqladmin
    environment:
      PMA_HOSTS: ekyc_db
      PMA_USER: root
      PMA_PASSWORD: root_password1
      PMA_ARBITRARY: 1
    ports:
      - "3401:80"
    depends_on:
      - mysql
